# Generated by Django 3.2.19 on 2025-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='latest_purchase_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
