# Generated by Django 3.2.19 on 2025-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_latest_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='initial_supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
