# Generated by Django 3.2.19 on 2025-03-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_initial_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(default='Repaired')),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='assets.asset')),
            ],
        ),
    ]
