# Generated by Django 3.2.19 on 2025-03-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('fixed asset', 'Fixed Asset'), ('current', 'Current Asset')], default='Current Asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('furniture', 'Furniture'), ('vehicle', 'Vehicle'), ('software', 'Software'), ('other', 'Other')], default='Equipment', max_length=100),
        ),
    ]
