# Generated by Django 3.2.19 on 2025-03-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20250330_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('fixed asset', 'Fixed Asset'), ('current asset', 'Current Asset')], default='Current Asset', max_length=20),
        ),
    ]
