# Generated by Django 5.2 on 2025-05-06 10:15

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings
import django.core.validators
from django.db.models import F

def generate_asset_tags(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    db_alias = schema_editor.connection.alias
    
    # Update assets without asset tags
    for index, asset in enumerate(Asset.objects.using(db_alias).filter(asset_tag__isnull=True), 1):
        while True:
            new_tag = f'ASSET-{index:05d}'
            if not Asset.objects.using(db_alias).filter(asset_tag=new_tag).exists():
                asset.asset_tag = new_tag
                asset.save()
                break
            index += 1

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0006_auto_20250330_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={
                'ordering': ['name'],
                'permissions': [
                    ('can_manage_assets', 'Can manage assets'),
                    ('can_view_assets', 'Can view assets'),
                    ('can_assign_assets', 'Can assign assets'),
                ],
            },
        ),
    ]
