# Generated by Django 3.2.19 on 2025-03-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20250326_1535'),
        ('inventory', '0002_auto_20250325_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.department'),
            preserve_default=False,
        ),
    ]
