# Generated by Django 3.2.19 on 2025-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='storeitem',
            unique_together={('store', 'item')},
        ),
    ]
