# Generated by Django 3.2.19 on 2025-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250330_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
