# Generated by Django 3.2.19 on 2025-04-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20250326_1535'),
        ('inventory', '0006_item_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemkit',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.department'),
            preserve_default=False,
        ),
    ]
