# Generated by Django 5.2 on 2025-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_auto_20250402_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemkit",
            name="cost_price",
            field=models.FloatField(default=0),
        ),
    ]
