# Generated by Django 5.2 on 2025-04-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_remove_itemkit_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.store",
            ),
        ),
    ]
