# Generated by Django 5.2 on 2025-04-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_adjustment_store"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemOtherUnit",
            new_name="ItemUnit",
        ),
        migrations.AddField(
            model_name="receiveditem",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.itemunit",
            ),
            preserve_default=False,
        ),
    ]
