# Generated by Django 5.2 on 2025-04-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_auto_20250326_1535"),
        ("inventory", "0011_rename_itemotherunit_itemunit_receiveditem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitionitem",
            name="available_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="total_cost",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.itemunit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="unit_cost",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requisition",
            name="approved_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisition_approved_by",
                to="company.employee",
            ),
        ),
    ]
