# Generated by Django 5.2 on 2025-04-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_auto_20250326_1535"),
        ("inventory", "0012_requisitionitem_available_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiving",
            name="requisition",
        ),
        migrations.AddField(
            model_name="receiveditem",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receiveditem",
            name="total_cost",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receiving",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receiving",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.store",
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="funded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requisition",
            name="funded_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisition_funded_by",
                to="company.employee",
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="funded_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="branch",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.branch",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SalePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=20)),
                ("status", models.CharField(default="Active", max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="company.branch"
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="receiving",
            name="sale_point",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.salepoint",
            ),
        ),
        migrations.CreateModel(
            name="SalePointItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
                (
                    "sale_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.salepoint",
                    ),
                ),
            ],
        ),
    ]
