# Generated by Django 5.2 on 2025-04-09 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0013_remove_receiving_requisition_receiveditem_department_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="sale_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.salepoint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salepointitem",
            unique_together={("sale_point", "item")},
        ),
    ]
