# Generated by Django 3.2.19 on 2025-04-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_adjustment_sale_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='sale_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salepoint'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='sale_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salepoint'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store'),
        ),
    ]
