# Generated by Django 3.2.19 on 2025-04-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20250410_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveditem',
            name='department',
        ),
    ]
