# Generated by Django 3.2.19 on 2025-04-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20250326_1535'),
        ('inventory', '0016_remove_receiveditem_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transfer_type', models.CharField(choices=[('store_to_store', 'Store to Store'), ('salepoint_to_salepoint', 'Sale Point to Sale Point'), ('salepoint_to_store', 'Sale Point to Store')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('from_salepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='inventory.salepoint')),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='inventory.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='to_shop',
        ),
        migrations.AddField(
            model_name='issue',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_completed', to='company.employee'),
        ),
        migrations.AddField(
            model_name='issue',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='sale_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.salepoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueditem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_approved', to='company.employee'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_requested', to='company.employee'),
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transfer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemunit')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='items',
            field=models.ManyToManyField(through='inventory.TransferItem', to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_salepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='inventory.salepoint'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee'),
        ),
    ]
