# Generated by Django 3.2.19 on 2025-04-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20250410_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueditem',
            name='total_cost',
        ),
    ]
