# Generated by Django 5.2 on 2025-05-07 11:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "company",
            "0007_employee_first_name_employee_last_name_employee_user_and_more",
        ),
        ("inventory", "0019_alter_item_options_alter_salepoint_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="buying_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
       
        migrations.AlterField(
            model_name="item",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("discontinued", "Discontinued"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        
        migrations.AlterField(
            model_name="salepoint",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="active",
                max_length=20,
            ),
        ),
       
        migrations.AlterField(
            model_name="supplier",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["bar_code"], name="inventory_i_bar_cod_aae266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status"], name="inventory_i_status_25f563_idx"),
        ),
    ]
