# Generated by Django 3.2.19 on 2025-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_description',
            field=models.TextField(default='Not given'),
            preserve_default=False,
        ),
    ]
