# Generated by Django 3.2.19 on 2025-03-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='company_id',
            new_name='company',
        ),
    ]
