# Generated by Django 3.2.19 on 2025-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20250326_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_designation',
            new_name='employee_position',
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(default='0717128286', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
