# Generated by Django 5.2 on 2025-05-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_auto_20250326_1535"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="Edmond", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="Zuberi", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_status",
            field=models.CharField(default="Active", max_length=20),
        ),
    ]
