# Generated by Django 5.2 on 2025-05-07 10:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_hours_start",
                    models.TimeField(help_text="Default start time for working hours"),
                ),
                (
                    "working_hours_end",
                    models.TimeField(help_text="Default end time for working hours"),
                ),
                (
                    "late_threshold_minutes",
                    models.IntegerField(
                        default=15,
                        help_text="Minutes after which an employee is considered late",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "early_leave_threshold_minutes",
                    models.IntegerField(
                        default=15,
                        help_text="Minutes before which an employee is considered leaving early",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "break_duration_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Default break duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Settings",
                "verbose_name_plural": "Attendance Settings",
            },
        ),
        migrations.CreateModel(
            name="FingerprintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_data",
                    models.BinaryField(help_text="Encrypted fingerprint template data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprint",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("break_start", "Break Start"),
                            ("break_end", "Break End"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("early_leave", "Early Leave"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("fingerprint_verified", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
                "unique_together": {("employee", "date", "attendance_type")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "total_working_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_break_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("early_leave", "Early Leave"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_leave", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendance Summaries",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
